import { prisma } from "@/config/database";
import bcrypt from "bcryptjs";

const CATEGORIES = [
  "Kata Benda",
  "Kata Benda/Sapaan",
  "Kata Bilangan",
  "Kata Buah",
  "Kata Depan",
  "Kata Ganti",
  "Kata Hari",
  "Kata Hewan",
  "Kata Hubung",
  "Kata Kerja",
  "Kata Kerja/Sifat",
  "Kata Keterangan",
  "Kata Seru",
  "Kata Sifat",
  "Kata Sifat/Kata Kerja",
  "Kata Tanya",
  "Kata Tempat",
  "Kata Tubuh",
  "Kata Tunjuk",
];

const WORDS: {
  localLanguage: string;
  indonesian: string;
  localScript: string;
  category: string;
}[] = [
  { localLanguage: "rapu", indonesian: "abu", localScript: "رَڨُو", category: "Kata Benda" },
  { localLanguage: "uwe", indonesian: "air", localScript: "ﺍُ ﻭَ ﻱِ", category: "Kata Benda" },
  { localLanguage: "usara", indonesian: "akar", localScript: "اوْسَرَ", category: "Kata Benda" },
  { localLanguage: "yaku", indonesian: "aku", localScript: "يَكُو", category: "Kata Ganti" },
  { localLanguage: "jala", indonesian: "alir(me)", localScript: "جَلاَ", category: "Kata Kerja" },
  { localLanguage: "Iko", indonesian: "Kamu", localScript: "اِكُو", category: "Kata Ganti" },
  { localLanguage: "aahera", indonesian: "akhirat", localScript: "اَاخٖيرَة", category: "Kata Benda" },
  { localLanguage: "aahiri", indonesian: "akhir", localScript: "اَاخٖيرِي", category: "Kata Keterangan" },
  { localLanguage: "aamani", indonesian: "aman", localScript: "اَامَانِي", category: "Kata Sifat" },
  { localLanguage: "acara", indonesian: "acara, acar(sayur)", localScript: "اَچَارَ", category: "Kata Benda" },
  { localLanguage: "ae", indonesian: "kaki", localScript: "اَيٖ", category: "Kata Benda" },
  { localLanguage: "ajala", indonesian: "ajal", localScript: "اَجَالَ", category: "Kata Benda" },
  { localLanguage: "ajima", indonesian: "azimat", localScript: "اَجٖيمَ", category: "Kata Benda" },
  { localLanguage: "alamati", indonesian: "alamat", localScript: "اَلَامَتِي", category: "Kata Benda" },
  { localLanguage: "alamu", indonesian: "alam", localScript: "اَلَامُو", category: "Kata Benda" },
  { localLanguage: "ana", indonesian: "anak", localScript: "اَنَ", category: "Kata Benda" },
  { localLanguage: "ngalu", indonesian: "angin", localScript: "غَالُو", category: "Kata Benda" },
  { localLanguage: "mantoa", indonesian: "anjing", localScript: "مَنْتٗوا", category: "Kata Benda" },
  { localLanguage: "opea", indonesian: "apa", localScript: "اٗوڤٖيا", category: "Kata Tanya" },
  { localLanguage: "lanto", indonesian: "apung", localScript: "لَنْتٗو", category: "Kata Sifat" },
  { localLanguage: "waa", indonesian: "api", localScript: "وَاء", category: "Kata Benda" },
  { localLanguage: "ombu", indonesian: "asap", localScript: "اٗوْمْبُو", category: "Kata Benda" },
  { localLanguage: "wolu", indonesian: "awan", localScript: "وٗولُو", category: "Kata Benda" },
  { localLanguage: "tuapa", indonesian: "bagaimana", localScript: "تُوَڤَ", category: "Kata Tanya" },
  { localLanguage: "malape", indonesian: "baik", localScript: "مَالَڤٖي", category: "Kata Sifat" },
  { localLanguage: "tunu", indonesian: "bakar", localScript: "تُوْنُو", category: "Kata Kerja" },
  { localLanguage: "balili", indonesian: "balik", localScript: "بَلٖيلٖي", category: "Kata Kerja" },
  { localLanguage: "bari", indonesian: "banyak", localScript: "بَارِي", category: "Kata Sifat" },
  { localLanguage: "ama", indonesian: "bapak", localScript: "اَمَ", category: "Kata Benda/Sapaan" },
  { localLanguage: "azabu", indonesian: "azab", localScript: "اَزَابُو", category: "Kata Benda" },
  { localLanguage: "bae", indonesian: "padi, beras", localScript: "بَيٖ", category: "Kata Benda" },
  { localLanguage: "baho", indonesian: "basah", localScript: "بَاهٗو", category: "Kata Sifat" },
  { localLanguage: "baga", indonesian: "pipi", localScript: "بَاغَ", category: "Kata Benda" },
  { localLanguage: "bhula", indonesian: "bulan", localScript: "بٖهُلَ", category: "Kata Benda" },
  { localLanguage: "bandera", indonesian: "bendera", localScript: "بَنْدٖيرَ", category: "Kata Benda" },
  { localLanguage: "bangasa", indonesian: "palak", localScript: "بَغَاسَ", category: "Kata Benda" },
  { localLanguage: "bangka", indonesian: "perahu", localScript: "بَغْكَ", category: "Kata Benda" },
  { localLanguage: "kandole-dole", indonesian: "baring", localScript: "كَنْدٗولٖي-دٗولٖي", category: "Kata Kerja" },
  { localLanguage: "baau", indonesian: "baru", localScript: "بَاءُو", category: "Kata Sifat" },
  { localLanguage: "magode", indonesian: "basah", localScript: "مَاغٗودٖي", category: "Kata Sifat" },
  { localLanguage: "batu", indonesian: "batu", localScript: "بَاتُو", category: "Kata Benda" },
  { localLanguage: "sagaa", indonesian: "beberapa", localScript: "سَاغَاء", category: "Kata Bilangan" },
  { localLanguage: "aweta", indonesian: "belah (me)", localScript: "اَوٖيتَ", category: "Kata Kerja" },
  { localLanguage: "totuu", indonesian: "benar", localScript: "تٗوتُوُو", category: "Kata Sifat" },
  { localLanguage: "tente", indonesian: "bengkak", localScript: "تٖنْتٖي", category: "Kata Sifat" },
  { localLanguage: "wine", indonesian: "benih", localScript: "وٖينٖي", category: "Kata Benda" },
  { localLanguage: "matamo", indonesian: "berat", localScript: "مَاتَمٗو", category: "Kata Sifat" },
  { localLanguage: "pongano", indonesian: "berenang", localScript: "ڤٗوغَانٗو", category: "Kata Kerja" },
  { localLanguage: "dawu", indonesian: "beri", localScript: "دَوُو", category: "Kata Kerja" },
  { localLanguage: "lingka", indonesian: "berjalan", localScript: "لٖيغْكَ", category: "Kata Kerja" },
  { localLanguage: "maoge", indonesian: "besar", localScript: "مَاوٗغٖي", category: "Kata Sifat" },
  { localLanguage: "ande", indonesian: "bilamana", localScript: "اَنْدٖي", category: "Kata Tanya" },
  { localLanguage: "binata", indonesian: "binatang", localScript: "بٖينَاتَ", category: "Kata Benda" },
  { localLanguage: "kalipopo", indonesian: "bintang", localScript: "كَالٖيْڤٗوڤٗو", category: "Kata Benda" },
  { localLanguage: "bhake", indonesian: "buah", localScript: "بٖهَاكٖي", category: "Kata Benda" },
  { localLanguage: "bulua", indonesian: "bulu", localScript: "بُوْلُوَا", category: "Kata Benda" },
  { localLanguage: "kamba", indonesian: "bunga", localScript: "كَمْبَ", category: "Kata Benda" },
  { localLanguage: "pekamate", indonesian: "bunuh", localScript: "ڤٖيكَمَاتٖي", category: "Kata Kerja" },
  { localLanguage: "madaki", indonesian: "buruk", localScript: "مَدَاكٖي", category: "Kata Sifat" },
  { localLanguage: "manu-manu", indonesian: "burung", localScript: "مَانُو-مَانُو", category: "Kata Benda" },
  { localLanguage: "mabuto", indonesian: "busuk", localScript: "مَبُوْتٗو", category: "Kata Sifat" },
  { localLanguage: "bhou", indonesian: "cium", localScript: "بٖهٗوْو", category: "Kata Kerja" },
  { localLanguage: "taphasi", indonesian: "cuci", localScript: "تَڤٖهَاسٖي", category: "Kata Kerja" },
  { localLanguage: "anto", indonesian: "daging", localScript: "اَنْتٗو", category: "Kata Benda" },
  { localLanguage: "te", indonesian: "dan", localScript: "تٖي", category: "Kata Hubung" },
  { localLanguage: "umala", indonesian: "danau", localScript: "اُمَالَ", category: "Kata Benda" },
  { localLanguage: "raa", indonesian: "darah", localScript: "رَاء", category: "Kata Benda" },
  { localLanguage: "kawa", indonesian: "datang", localScript: "كَاوَ", category: "Kata Kerja" },
  { localLanguage: "lae", indonesian: "daun", localScript: "لَيٖ", category: "Kata Benda" },
  { localLanguage: "ngawu", indonesian: "debu", localScript: "غَاوُو", category: "Kata Benda" },
  { localLanguage: "makasu", indonesian: "dekat", localScript: "مَكَاسُو", category: "Kata Sifat" },
  { localLanguage: "rango", indonesian: "dengar", localScript: "رَغٗو", category: "Kata Kerja" },
  { localLanguage: "ginunca", indonesian: "di  dalam", localScript: "غٖينُنْچَ", category: "Kata Depan" },
  { localLanguage: "wesyi", indonesian: "di sini", localScript: "وٖيسْيٖي", category: "Kata Tunjuk" },
  { localLanguage: "weitu", indonesian: "di situ", localScript: "وٖيٖيْتُو", category: "Kata Tunjuk" },
  { localLanguage: "yapai", indonesian: "dimana", localScript: "يَڤَي", category: "Kata Tanya" },
  { localLanguage: "magari", indonesian: "dingin", localScript: "مَاغَارِي", category: "Kata Sifat" },
  { localLanguage: "cabo", indonesian: "sabun", localScript: "چَابٗو", category: "Kata Benda" },
  { localLanguage: "cahea", indonesian: "cahaya", localScript: "چَهٖيَا", category: "Kata Benda" },
  { localLanguage: "cere", indonesian: "cerek", localScript: "چٖيرٖي", category: "Kata Benda" },
  { localLanguage: "daangia", indonesian: "ada", localScript: "دَاءغٖيَا", category: "Kata Kerja" },
  { localLanguage: "dangiapo", indonesian: "masih ada", localScript: "دَغٖيَاڤٗو", category: "Kata Kerja" },
  { localLanguage: "dangku", indonesian: "terbentur", localScript: "دَغْكُو", category: "Kata Kerja" },
  { localLanguage: "jujuraa", indonesian: "dorong", localScript: "جُوْجُوْرَاء", category: "Kata Kerja" },
  { localLanguage: "rua", indonesian: "dua", localScript: "رُوَا", category: "Kata Bilangan" },
  { localLanguage: "ncura", indonesian: "duduk", localScript: "نْچُوْرَ", category: "Kata Kerja" },
  { localLanguage: "lenci", indonesian: "ekor", localScript: "لٖينْچٖي", category: "Kata Benda" },
  { localLanguage: "pata", indonesian: "empat", localScript: "ڤَاتَ", category: "Kata Bilangan" },
  { localLanguage: "yingko", indonesian: "engkau", localScript: "يٖيغْكٗو", category: "Kata Ganti" },
  { localLanguage: "seli", indonesian: "gali", localScript: "سٖيلٖي", category: "Kata Kerja" },
  { localLanguage: "gara", indonesian: "garam", localScript: "غَارَ", category: "Kata Benda" },
  { localLanguage: "kangkanu", indonesian: "garuk", localScript: "كَغْكَنُو", category: "Kata Kerja" },
  { localLanguage: "malompo", indonesian: "gemuk", localScript: "مَلٗومْڤٗو", category: "Kata Sifat" },
  { localLanguage: "nginci", indonesian: "gigi", localScript: "غٖينْچٖي", category: "Kata Benda" },
  { localLanguage: "papaki", indonesian: "gigit", localScript: "ڤَاڤَكٖي", category: "Kata Kerja" },
  { localLanguage: "kikisi", indonesian: "gosok", localScript: "كٖيكٖيسٖي", category: "Kata Kerja" },
  { localLanguage: "gunu", indonesian: "gunung", localScript: "غُوْنُو", category: "Kata Benda" },
  { localLanguage: "tapako", indonesian: "hantam", localScript: "تَڤَاكٗو", category: "Kata Kerja" },
  { localLanguage: "hapusu", indonesian: "hapus", localScript: "هَڤُوْسُو", category: "Kata Kerja" },
  { localLanguage: "ngangaranda", indonesian: "hati", localScript: "غَاغَارَنْدَ", category: "Kata Benda" },
  { localLanguage: "ango", indonesian: "hidung", localScript: "اَغٗو", category: "Kata Benda" },
  { localLanguage: "dadi", indonesian: "hidup", localScript: "دَادِي", category: "Kata Kerja/Sifat" },
  { localLanguage: "ijo", indonesian: "hijau", localScript: "اٖيجٗو", category: "Kata Sifat" },
  { localLanguage: "gomi", indonesian: "hisap", localScript: "غٗومٖي", category: "Kata Kerja" },
  { localLanguage: "maeta", indonesian: "hitam", localScript: "مَيٖتَ", category: "Kata Sifat" },
  { localLanguage: "gagari", indonesian: "hitung", localScript: "غَاغَارِي", category: "Kata Kerja" },
  { localLanguage: "kowao", indonesian: "hujan", localScript: "كٗووَاوٗو", category: "Kata Benda" },
  { localLanguage: "koo", indonesian: "hutan", localScript: "كٗوْو", category: "Kata Benda" },
  { localLanguage: "yincia", indonesian: "ia", localScript: "يٖينْچٖيَا", category: "Kata Ganti" },
  { localLanguage: "ina", indonesian: "ibu", localScript: "اٖينَ", category: "Kata Benda/Sapaan" },
  { localLanguage: "ikane", indonesian: "ikan", localScript: "اٖيكَنٖي", category: "Kata Benda" },
  { localLanguage: "siy", indonesian: "ini", localScript: "سٖي", category: "Kata Tunjuk" },
  { localLanguage: "bhawine", indonesian: "istri", localScript: "بٖهَاوٖينٖي", category: "Kata Benda" },
  { localLanguage: "syitu", indonesian: "itu", localScript: "سْيٖيْتُو", category: "Kata Tunjuk" },
  { localLanguage: "garangga", indonesian: "agar-agar", localScript: "غَرَغْغَ", category: "Kata Benda" },
  { localLanguage: "basaraa", indonesian: "agung", localScript: "بَسَرَاء", category: "Kata Sifat" },
  { localLanguage: "yaakutu", indonesian: "batu permata", localScript: "يَاءكُوْتُو", category: "Kata Benda" },
  { localLanguage: "saopea", indonesian: "berapa", localScript: "سَاٗوڤٖيَا", category: "Kata Tanya" },
  { localLanguage: "singkaru", indonesian: "cincin", localScript: "سٖيغْكَارُو", category: "Kata Benda" },
  { localLanguage: "hakeekati", indonesian: "hakikat", localScript: "هَكٖيْكَاتٖي", category: "Kata Benda" },
  { localLanguage: "raraea", indonesian: "hari raya", localScript: "رَرَايٖءَا", category: "Kata Benda" },
  { localLanguage: "lentu", indonesian: "hitung", localScript: "لٖينْتُو", category: "Kata Kerja" },
  { localLanguage: "kagarai", indonesian: "ikan asin", localScript: "كَاغَرَاي", category: "Kata Benda" },
  { localLanguage: "isilamu", indonesian: "islam", localScript: "اٖيسٖيلَامُو", category: "Kata Benda" },
  { localLanguage: "kaitela", indonesian: "jagung", localScript: "كَيٖتٖيلَ", category: "Kata Benda" },
  { localLanguage: "tombo", indonesian: "jambu air", localScript: "تٗومْبٗو", category: "Kata Benda" },
  { localLanguage: "bulamalaka", indonesian: "jambu biji", localScript: "بُوْلَمَالَاكَ", category: "Kata Benda" },
  { localLanguage: "kuwu", indonesian: "jamur", localScript: "كُوْوُو", category: "Kata Benda" },
  { localLanguage: "asala", indonesian: "jangan sampai", localScript: "اَسَالَ", category: "Kata Seru" },
  { localLanguage: "jini", indonesian: "jin", localScript: "جٖينٖي", category: "Kata Benda" },
  { localLanguage: "jiwa", indonesian: "jiwa", localScript: "جٖيوَ", category: "Kata Benda" },
  { localLanguage: "joge", indonesian: "joget", localScript: "جٗوغٖي", category: "Kata Kerja" },
  { localLanguage: "jumaa", indonesian: "jumat", localScript: "جُوْمَاء", category: "Kata Benda" },
  { localLanguage: "kapala", indonesian: "kapal", localScript: "كَڤَالَ", category: "Kata Benda" },
  { localLanguage: "kaudawa", indonesian: "kelor", localScript: "كَاوْدَاوَ", category: "Kata Benda" },
  { localLanguage: "buntuli", indonesian: "lari", localScript: "بُنْتُوْلٖي", category: "Kata Kerja" },
];

const WORDS_XLSX: {
  localLanguage: string;
  indonesian: string;
  localScript: string;
  category: string;
}[] = [
  { localLanguage: "karo", indonesian: "tubuh, diri", localScript: "كَارُو", category: "Kata Benda" },
  { localLanguage: "Aahera basaraa", indonesian: "Akhirat yang agung", localScript: "اَا ٖخي َرةَ بَسَراءَ", category: "Kata Keterangan" },
  { localLanguage: "kasoro", indonesian: "kasur", localScript: "كَاسُرُو", category: "Kata Benda" },
  { localLanguage: "Acara raraea", indonesian: "Acara hari raya", localScript: "اَچاَرَ رَراٖيءَ", category: "Kata Keterangan" },
  { localLanguage: "ndala, mandala", indonesian: "dalam", localScript: "نْدَالَ / مَنْدَالَ", category: "Kata Keterangan" },
  { localLanguage: "Ae tente", indonesian: "Kaki bengkak", localScript: "اَي تِيْنْتِي", category: "Kata Keterangan" },
  { localLanguage: "sunati", indonesian: "sunat", localScript: "سُونَاتِي", category: "Kata Kerja" },
  { localLanguage: "Ajima singkaru", indonesian: "Azimat cincin", localScript: "اَٖجيمَ سِيٖغْكَارُو", category: "Kata Benda" },
  { localLanguage: "aebu", indonesian: "aib", localScript: "اَيْبُ", category: "Kata Benda" },
  { localLanguage: "Akhiri zamani", indonesian: "Akhir zaman", localScript: "اَا خِيرِي زَمَانِي", category: "Kata Keterangan" },
  { localLanguage: "agaati", indonesian: "memisah", localScript: "اَڬَاَتِي", category: "Kata Kerja" },
  { localLanguage: "Akhiri zamani fitanaa", indonesian: "Akhir zaman penuh fitnah.", localScript: "اَاخِيرِي زَمَانِي فِتْنَة", category: "Kata Keterangan" },
  { localLanguage: "agadhe", indonesian: "berjualan", localScript: "اَڬَدْهَ", category: "Kata Kerja" },
  { localLanguage: "Alamu maoge", indonesian: "Alam yang besar", localScript: "اَلَموُ مَاٗوٖغي", category: "Kata Keterangan" },
  { localLanguage: "aba", indonesian: "tanya", localScript: "اَبَا", category: "Kata Tanya" },
  { localLanguage: "Ama ncura", indonesian: "Ayah duduk", localScript: "اَمَا ْنُچُرَ", category: "Kata Kerja" },
  { localLanguage: "abi", indonesian: "gelar", localScript: "اَبِي", category: "Kata Keterangan" },
  { localLanguage: "Ama rango yaku", indonesian: "Ayah mendengar saya", localScript: "اَمَا رَغُو يَكُو", category: "Kata Keterangan" },
  { localLanguage: "ade", indonesian: "dagu", localScript: "اَدَيْ", category: "Kata Benda" },
  { localLanguage: "Ama zikiri wesyi", indonesian: "Ayah berzikir di sini.", localScript: "اَمَا ذِكِرِي وٖيسِي", category: "Kata Kerja" },
  { localLanguage: "adede", indonesian: "aduh", localScript: "اَدَدَيْ", category: "Kata Kerja" },
  { localLanguage: "Ama, mai manga", indonesian: "Ayah, mari makan.", localScript: "اَمَا، مَاي مَغَا", category: "Kata Kerja" },
  { localLanguage: "adencu", indonesian: "bergeser", localScript: "اَدَنْچُ", category: "Kata Kerja" },
  { localLanguage: "Ana lingka", indonesian: "Anak berjalan", localScript: "اَنَ لِيْغْكَا", category: "Kata Kerja" },
  { localLanguage: "adhabu", indonesian: "kutukan", localScript: "اَدْهَابُ", category: "Kata Keterangan" },
  { localLanguage: "Ana malape", indonesian: "Anak baik", localScript: "اَنَ مَلَڤِي", category: "Kata Keterangan" },
  { localLanguage: "ago", indonesian: "selamatkan", localScript: "اَڬُو", category: "Kata Kerja" },
  { localLanguage: "Ango baho", indonesian: "Hidung basah", localScript: "اَٗغو بَاهٗو", category: "Kata Keterangan" },
  { localLanguage: "agoago", indonesian: "buru-buru", localScript: "اَڬُوَاڬُو", category: "Kata Kerja" },
  { localLanguage: "Bae bari", indonesian: "Padi banyak", localScript: "بَي بَارِي", category: "Kata Keterangan" },
  { localLanguage: "agoi", indonesian: "rampas", localScript: "اَڬُوِي", category: "Kata Kerja" },
  { localLanguage: "Bae dawu", indonesian: "Memberi padi", localScript: "بَي دَاوُو", category: "Kata Keterangan" },
  { localLanguage: "agorampangi", indonesian: "menggertak", localScript: "اَڬُرَمْڤَنْڬِي", category: "Kata Kerja" },
  { localLanguage: "Bandera wesyi", indonesian: "Bendera di sini", localScript: "بَْنٖديْرَ وٖيْسيٖ", category: "Kata Keterangan" },
  { localLanguage: "agua", indonesian: "membangkang", localScript: "اَڬُوَا", category: "Kata Sifat" },
  { localLanguage: "Bangka kawa", indonesian: "Perahu datang", localScript: "بَغْكَ كَاوَ", category: "Kata Keterangan" },
  { localLanguage: "ahadhi", indonesian: "ahad,minggu", localScript: "اَهَدْهِ", category: "Kata Hari" },
  { localLanguage: "Batu maeta", indonesian: "Batu hitam", localScript: "بَاتُو مَيْتَ", category: "Kata Benda" },
  { localLanguage: "ahali", indonesian: "ahli", localScript: "اَهَالِي", category: "Kata Keterangan" },
  { localLanguage: "Bhake bari", indonesian: "Buah banyak", localScript: "بَهَكِي بَارِي", category: "Kata Keterangan" },
  { localLanguage: "ahama", indonesian: "bodoh", localScript: "اَهَامَ", category: "Kata Sifat" },
  { localLanguage: "Bhawine ncura", indonesian: "Istri duduk", localScript: "بَٖهاٖوينيٖ ْنُچُرَ", category: "Kata Kerja" },
  { localLanguage: "ahejaia", indonesian: "dieja", localScript: "اَهَيْجَايَا", category: "Kata Kerja" },
  { localLanguage: "Binata lingka", indonesian: "Binatang berjalan", localScript: "بٖينَتَ لِيٖغْكَ", category: "Kata Kerja" },
  { localLanguage: "ahojaia", indonesian: "difitnah", localScript: "اَهُوجَايَا", category: "Kata Sifat" },
  { localLanguage: "Bulua baho", indonesian: "Bulu basah", localScript: "بُوْلُوا بَاهٗو", category: "Kata Keterangan" },
  { localLanguage: "ajala", indonesian: "ajal", localScript: "اَجَالَ", category: "Kata Benda" },
  { localLanguage: "Cabo taphasi", indonesian: "Sabun untuk mencuci", localScript: "چَابٗو تَٖڤَهاٖسي", category: "Kata Benda" },
  { localLanguage: "ajara", indonesian: "kuda", localScript: "اَجَارَ", category: "Kata Benda" },
  { localLanguage: "Cahea bhula", indonesian: "Cahaya bulan", localScript: "چَهِيَ بُهُلَ", category: "Kata Benda" },
  { localLanguage: "ajo", indonesian: "rias", localScript: "اَجُو", category: "Kata Sifat" },
  { localLanguage: "Cahea bhula", indonesian: "Cahaya bulan", localScript: "چٖهيَ بُٖهَل", category: "Kata Benda" },
  { localLanguage: "aka", indonesian: "kakak", localScript: "اَكَا", category: "Kata Sifat" },
  { localLanguage: "Cere wesyi", indonesian: "Cerek di sini", localScript: "چٖيٖر وٖيْسيٖ", category: "Kata Benda" },
  { localLanguage: "akala", indonesian: "akal", localScript: "اَكَلَ", category: "Kata Sifat" },
  { localLanguage: "Daangia wesyi", indonesian: "Ada di sini", localScript: "دَاءٖغيَ وٖيْسيٖ", category: "Kata Keterangan" },
  { localLanguage: "alemari", indonesian: "lemari", localScript: "اَلَمَارِي", category: "Kata Benda" },
  { localLanguage: "Dadi aamani", indonesian: "Hidup aman", localScript: "دَادِي اَامَانِي", category: "Kata Keterangan" },
  { localLanguage: "amaelumo", indonesian: "telah piatu", localScript: "اَمَايْلُمُو", category: "Kata Keterangan" },
  { localLanguage: "Dangiapo weitu", indonesian: "Masih ada di situ", localScript: "دَٖغيَڤٗا وٖيٖيتُو", category: "Kata Keterangan" },
  { localLanguage: "amaijo", indonesian: "menghijau", localScript: "اَمَايْجُو", category: "Kata Keterangan" },
  { localLanguage: "Dhoi bari", indonesian: "Uang banyak", localScript: "دُوِي بَارِي", category: "Kata Keterangan" },
  { localLanguage: "amala", indonesian: "amal", localScript: "اَمَلَ", category: "Kata Sifat" },
  { localLanguage: "Dhosa fitanaa", indonesian: "Dosa fitnah", localScript: "دُوسَا فِتْنَة", category: "Kata Keterangan" },
  { localLanguage: "amara", indonesian: "marah", localScript: "اَمَرَ", category: "Kata Sifat" },
  { localLanguage: "Ebaho wesyi", indonesian: "Mandi di sini", localScript: "اٖبَاهُو وٖيسِي", category: "Kata Kerja" },
  { localLanguage: "anbia", indonesian: "para nabi", localScript: "اَنْبِيَا", category: "Kata Keterangan" },
  { localLanguage: "Embere baho", indonesian: "Ember basah", localScript: "اٖمْبٖرٖ بَاهُو", category: "Kata Benda" },
  { localLanguage: "apolele", indonesian: "menyampaikan berita", localScript: "اَڤُولَلَيْ", category: "Kata Kerja" },
  { localLanguage: "Ende maoge", indonesian: "Loncatan besar", localScript: "اٖنْدٖ مَاوْغٖ", category: "Kata Kerja" },
  { localLanguage: "araba'a", indonesian: "rabu", localScript: "اَرَبَعَ", category: "Kata Hari" },
  { localLanguage: "Ene bae", indonesian: "Memungut padi", localScript: "اٖنٖ بَي", category: "Kata Kerja" },
  { localLanguage: "arabu", indonesian: "arab", localScript: "اَرَبُ", category: "Kata Keterangan" },
  { localLanguage: "Ewo maoge", indonesian: "Ombak besar", localScript: "اٖوُو مَاوْغٖ", category: "Kata Keterangan" },
  { localLanguage: "arope", indonesian: "menuju", localScript: "اَرُڤَيْ", category: "Kata Kerja" },
  { localLanguage: "Faaedha bari", indonesian: "Banyak manfaat", localScript: "فَائِدَة بَارِي", category: "Kata Keterangan" },
  { localLanguage: "baau", indonesian: "baru", localScript: "بَااوُ", category: "Kata Keterangan" },
  { localLanguage: "Faasiki dhosa", indonesian: "Kejahatan yang berdosa", localScript: "فَاسِكِي دُوسَا", category: "Kata Keterangan" },
  { localLanguage: "baba", indonesian: "berkas", localScript: "بَابَا", category: "Kata Benda" },
  { localLanguage: "Fabereki maoge", indonesian: "Pabrik besar", localScript: "فَبٖرٖكِي مَاوْغٖ", category: "Kata Benda" },
  { localLanguage: "babe", indonesian: "kacau", localScript: "بَابَيْ", category: "Kata Sifat" },
  { localLanguage: "Fadhuli yincia", indonesian: "Ia peduli", localScript: "فَضُولِي يِنْچِيَا", category: "Kata Sifat" },
  { localLanguage: "babu", indonesian: "babu", localScript: "بَابُ", category: "Kata Benda" },
  { localLanguage: "Fahamu hakeekati", indonesian: "Memahami hakikat", localScript: "فَهَمُو هَكِيكَتِي", category: "Kata Kerja" },
  { localLanguage: "baca", indonesian: "baca", localScript: "بَچَا", category: "Kata Kerja" },
  { localLanguage: "Fajara cahea", indonesian: "Cahaya fajar", localScript: "فَجَرَ چَهٖيَا", category: "Kata Keterangan" },
  { localLanguage: "baco", indonesian: "pesuruh", localScript: "بَچُو", category: "Kata Kerja" },
  { localLanguage: "Faraluu zikiri", indonesian: "Perlu berzikir", localScript: "فَرَلُو زِكِيرِي", category: "Kata Kerja" },
  { localLanguage: "badha", indonesian: "badan", localScript: "بَدْهَ", category: "Kata Keterangan" },
  { localLanguage: "Faraluu zikiri", indonesian: "Perlu berzikir", localScript: "فَرَلُو ذِكِرِي", category: "Kata Kerja" },
  { localLanguage: "badili", indonesian: "meriam", localScript: "بَدِلِي", category: "Kata Benda" },
  { localLanguage: "Fasala fitanaa", indonesian: "Pasal tentang fitnah", localScript: "فَصَلَ فِتْنَة", category: "Kata Keterangan" },
  { localLanguage: "bado-bado", indonesian: "badut", localScript: "بَدُوْبَدُو", category: "Kata Sifat" },
  { localLanguage: "Fikiri hakeekati", indonesian: "Memikirkan hakikat", localScript: "فِكِرِي هَكِيكَتِي", category: "Kata Keterangan" },
  { localLanguage: "bagoea", indonesian: "goncang", localScript: "بَاڬُوَيَا", category: "Kata Kerja" },
  { localLanguage: "Fitanaa dhosa", indonesian: "Fitnah yang berdosa", localScript: "فِتْنَة دُوسَا", category: "Kata Keterangan" },
  { localLanguage: "baguli", indonesian: "kelereng", localScript: "بَاڬُلِي", category: "Kata Benda" },
  { localLanguage: "Gara bari", indonesian: "Garam banyak", localScript: "غَر بَاِري", category: "Kata Benda" },
  { localLanguage: "baha", indonesian: "bahak", localScript: "بَهَا", category: "Kata Kerja" },
  { localLanguage: "Gunu maeta", indonesian: "Gunung hitam", localScript: "غُونُو مَيْتَ", category: "Kata Keterangan" },
  { localLanguage: "bahahai", indonesian: "gertakan", localScript: "بَهَاهَاي", category: "Kata Kerja" },
  { localLanguage: "Gunu maoge", indonesian: "Gunung besar", localScript: "غُوْنُو مَاٗوٖغي", category: "Kata Keterangan" },
  { localLanguage: "bahatiki", indonesian: "jenaka", localScript: "بَهَاتِكِي", category: "Kata Sifat" },
  { localLanguage: "Hakeekati isilamu", indonesian: "Hakikat Islam", localScript: "هٖكْيَكاٖتي اِيٖسيَلَمُو", category: "Kata Keterangan" },
  { localLanguage: "baho", indonesian: "basah", localScript: "بَهُو", category: "Kata Sifat" },
  { localLanguage: "Hilafu dhosa", indonesian: "Khilaf dan berdosa", localScript: "خِلَافُ دُوسَا", category: "Kata Keterangan" },
  { localLanguage: "baiki", indonesian: "panu", localScript: "بَايْكِي", category: "Kata Sifat" },
  { localLanguage: "Hilafu fadhuli", indonesian: "Khilaf tetapi masih peduli.", localScript: "خِلَافُ فَضُولِي", category: "Kata Keterangan" },
  { localLanguage: "baila", indonesian: "burik", localScript: "بَايْلَ", category: "Kata Benda" },
  { localLanguage: "Ikane baho", indonesian: "Ikan basah", localScript: "اِيْكَني بَاهُو", category: "Kata Kerja" },
  { localLanguage: "baja", indonesian: "benang", localScript: "بَاجَا", category: "Kata Benda" },
  { localLanguage: "Ikane pongano", indonesian: "Ikan berenang", localScript: "اِيْكَني ڤُغَانُو", category: "Kata Kerja" },
  { localLanguage: "baju", indonesian: "baju", localScript: "بَاجُ", category: "Kata Benda" },
  { localLanguage: "Iko fahamu fasala", indonesian: "Kamu memahami pasal.", localScript: "اِكُو فَهَمُو فَصَلَ", category: "Kata Keterangan" },
  { localLanguage: "baka", indonesian: "debar", localScript: "بَاكَا", category: "Kata Sifat" },
  { localLanguage: "Iko kawa", indonesian: "Kamu datang", localScript: "اِكُو كَاوَ", category: "Kata Kerja" },
  { localLanguage: "bakaa", indonesian: "kekal", localScript: "بَاكَاا", category: "Kata Sifat/Kata Kerja" },
  { localLanguage: "Iko rango yincia", indonesian: "Kamu mendengar dia", localScript: "اِكُو رَغُو يِنْچِيَ", category: "Kata Kerja" },
  { localLanguage: "bake", indonesian: "buah", localScript: "بَاكَيْ", category: "Kata Benda" },
  { localLanguage: "Ina dawu bae", indonesian: "Ibu memberi padi", localScript: "اِيْنَ دَاوُو بَي", category: "Kata Kerja" },
  { localLanguage: "baki", indonesian: "keranjang", localScript: "بَاكِي", category: "Kata Benda" },
  { localLanguage: "Ina kawa", indonesian: "Ibu datang", localScript: "اِيْنَ كَاوَ", category: "Kata Kerja" },
  { localLanguage: "balaa", indonesian: "kecelakaan", localScript: "بَالَاا", category: "Kata Kerja" },
  { localLanguage: "Ina ziara weitu", indonesian: "Ibu berziarah di situ.", localScript: "اِينَا زِيَارَ وٖيتُو", category: "Kata Kerja" },
  { localLanguage: "balaba", indonesian: "jurus dalam persilatan", localScript: "بَالَابَا", category: "Kata Kerja" },
  { localLanguage: "Ina, mai manga", indonesian: "Ibu, mari makan.", localScript: "اِينَا، مَاي مَغَا", category: "Kata Kerja" },
  { localLanguage: "balaca", indonesian: "belacang", localScript: "بَالَچَا", category: "Kata Benda" },
  { localLanguage: "Jini weitu", indonesian: "Jin di situ", localScript: "جيٖني وٖيٖيتُو", category: "Kata Keterangan" },
  { localLanguage: "balai", indonesian: "balia", localScript: "بَالَاي", category: "Kata Benda" },
  { localLanguage: "Kaitela bari", indonesian: "Jagung banyak", localScript: "كَيْتِيْلَ بَارِي", category: "Kata Benda" },
  { localLanguage: "balase", indonesian: "belase", localScript: "بَالَاسَيْ", category: "Kata Depan" },
  { localLanguage: "Kamba cahea", indonesian: "Bunga bercahaya", localScript: "كَمْبَ چَهِيَ", category: "Kata Keterangan" },
  { localLanguage: "bale", indonesian: "tegak", localScript: "بَالَيْ", category: "Kata Kerja" },
  { localLanguage: "Kapala kawa", indonesian: "Kapal datang", localScript: "كَڤَلَ كَاوَ", category: "Kata Kerja" },
  { localLanguage: "bali", indonesian: "lawan", localScript: "بَالِي", category: "Kata Benda" },
  { localLanguage: "Koo maoge", indonesian: "Hutan besar", localScript: "كُو مَاوْغِي", category: "Kata Keterangan" },
  { localLanguage: "bali", indonesian: "kapak kecil gagang pendek", localScript: "بَالِي", category: "Kata Benda" },
  { localLanguage: "Kowao wesyi", indonesian: "Hujan di sini", localScript: "كُوَاوَ وِيْسِي", category: "Kata Keterangan" },
  { localLanguage: "balida", indonesian: "parang panjang", localScript: "بَالِدَا", category: "Kata Kerja" },
  { localLanguage: "Lae ijo", indonesian: "Daun hijau", localScript: "لَي اِجُو", category: "Kata Keterangan" },
  { localLanguage: "balika", indonesian: "putaran arus", localScript: "بَالِكَا", category: "Kata Sifat" },
  { localLanguage: "Mai lingka", indonesian: "Ayo pergi jalan", localScript: "مَاي لِيٖغْكَ", category: "Kata Kerja" },
  { localLanguage: "balo", indonesian: "lubang", localScript: "بَالُو", category: "Kata Sifat" },
  { localLanguage: "Mai manga", indonesian: "Mari makan.", localScript: "مَاي مَغَا", category: "Kata Kerja" },
  { localLanguage: "balobalo", indonesian: "jendela", localScript: "بَالُوبَالُو", category: "Kata Benda" },
  { localLanguage: "Mantoa buntuli", indonesian: "Anjing berlari", localScript: "مَنْتُوا بُنْتُوْلِي", category: "Kata Kerja" },
  { localLanguage: "balobu", indonesian: "pasu", localScript: "بَالُوبُ", category: "Kata Benda" },
  { localLanguage: "Mantoa malompo", indonesian: "Anjing gemuk", localScript: "مَنْتُوا مَلُمْڤُو", category: "Kata Keterangan" },
  { localLanguage: "balongka", indonesian: "belang", localScript: "بَالُونْڬَكَا", category: "Kata Sifat" },
  { localLanguage: "Manu-manu lingka", indonesian: "Burung berjalan", localScript: "مَنُو-مَنُو لِيْغْكَا", category: "Kata Kerja" },
  { localLanguage: "balu", indonesian: "kafan", localScript: "بَالُ", category: "Kata Benda" },
  { localLanguage: "Manu-manu pongano", indonesian: "Burung berenang", localScript: "مَنُو-مَنُو ڤُغَانُو", category: "Kata Keterangan" },
  { localLanguage: "balula", indonesian: "belulang", localScript: "بَالُلَ", category: "Kata Benda" },
  { localLanguage: "Ngalu kowao", indonesian: "Angin hujan", localScript: "غَالُو كُوَاوَ", category: "Kata Keterangan" },
  { localLanguage: "balumbi", indonesian: "belimbing", localScript: "بَالُمْبِي", category: "Kata Buah" },
  { localLanguage: "Nginci papaki anto", indonesian: "Gigi menggigit daging", localScript: "غِيْنْچِي ڤَڤَكِي اَنْتُو", category: "Kata Keterangan" },
  { localLanguage: "banci", indonesian: "benci", localScript: "بَنْچِي", category: "Kata Sifat" },
  { localLanguage: "Ombu waa", indonesian: "Asap api", localScript: "اُمْبُو وَاءَ", category: "Kata Keterangan" },
  { localLanguage: "bandara", indonesian: "bandar", localScript: "بَنْدَارَ", category: "Kata Tempat" },
  { localLanguage: "Raa baho", indonesian: "Darah basah", localScript: "رَاءَ بَاهُو", category: "Kata Keterangan" },
  { localLanguage: "bandera", indonesian: "bendera", localScript: "بَنْدَرَ", category: "Kata Benda" },
  { localLanguage: "Singkaru ajima", indonesian: "Cincin azimat", localScript: "سِيْغْكَارُو اَجِيمَ", category: "Kata Benda" },
  { localLanguage: "bangasa", indonesian: "palak", localScript: "بَنْڬَاسَ", category: "Kata Benda" },
  { localLanguage: "Umala wesyi", indonesian: "Danau di sini", localScript: "اُمَلَ وِيْسِي", category: "Kata Keterangan" },
  { localLanguage: "bangke", indonesian: "bangkai", localScript: "بَنْڬَيْ", category: "Kata Benda" },
  { localLanguage: "Uwe jala", indonesian: "Air mengalir", localScript: "اُوَي جَلَا", category: "Kata Kerja" },
  { localLanguage: "bangko", indonesian: "bangku", localScript: "بَنْڬُو", category: "Kata Benda" },
  { localLanguage: "Waa tunu", indonesian: "Api membakar", localScript: "وَاءَ تُنُو", category: "Kata Keterangan" },
  { localLanguage: "bangkudu", indonesian: "bengkudu", localScript: "بَنْڬُدُ", category: "Kata Buah" },
  { localLanguage: "Wolu kowao", indonesian: "Awan hujan", localScript: "وُولُو كُوَاوَ", category: "Kata Keterangan" },
  { localLanguage: "bangkuru", indonesian: "bangkrut", localScript: "بَنْڬُرُ", category: "Kata Keterangan" },
  { localLanguage: "Yaku fahamu hakeekati", indonesian: "Saya memahami hakikat.", localScript: "يَكُو فَهَمُو هَكِيكَتِي", category: "Kata Keterangan" },
  { localLanguage: "bangu", indonesian: "bangun", localScript: "بَانْڬُ", category: "Kata Kerja" },
  { localLanguage: "Yaku ncura", indonesian: "Saya duduk", localScript: "يَكُو ْنُچُرَ", category: "Kata Kerja" },
  { localLanguage: "bangule", indonesian: "kencur", localScript: "بَانْڬُلَيْ", category: "Kata Buah" },
  { localLanguage: "Yaku wesyi", indonesian: "Saya di sini", localScript: "يَكُو وِيْسِي", category: "Kata Keterangan" },
  { localLanguage: "bangunsaa", indonesian: "wibawa", localScript: "بَانْڬُنْسَاا", category: "Kata Sifat" },
  { localLanguage: "Yincia ebaho wesyi", indonesian: "Ia mandi di sini.", localScript: "يِنْچِيَا اٖبَاهُو وٖيسِي", category: "Kata Keterangan" },
  { localLanguage: "bantaa", indonesian: "kambuh", localScript: "بَنْتَاا", category: "Kata Sifat" },
  { localLanguage: "Yincia lingka", indonesian: "Ia berjalan", localScript: "يِنْچِيَ لِيْغْكَا", category: "Kata Benda" },
  { localLanguage: "bantara", indonesian: "terlantar", localScript: "بَنْتَارَ", category: "Kata Kerja" },
  { localLanguage: "Yincia weitu", indonesian: "Dia di situ", localScript: "يِنْچِيَ وِيْتُو", category: "Kata Keterangan" },
  { localLanguage: "bantila", indonesian: "tempat penggilingan padi", localScript: "بَنْتِلَ", category: "Kata Benda" },
  { localLanguage: "Zaalimu dhosa", indonesian: "Orang zalim yang berdosa", localScript: "ظَالِمُ دُوسَا", category: "Kata Keterangan" },
  { localLanguage: "bantua", indonesian: "bantuan", localScript: "بَنْتُوَا", category: "Kata Kerja" },
  { localLanguage: "Zamani aahiri", indonesian: "Zaman akhir", localScript: "زَمَانِي اَاخِيرِي", category: "Kata Keterangan" },
  { localLanguage: "banui", indonesian: "cuci", localScript: "بَانُوِي", category: "Kata Kerja" },
  { localLanguage: "Zamzamu uwe", indonesian: "Air zamzam", localScript: "زَمْزَمُو اُوَي", category: "Kata Benda" },
  { localLanguage: "bara", indonesian: "berat, kiranya", localScript: "بَارَ", category: "Kata Keterangan" },
  { localLanguage: "Ziara raraea", indonesian: "Ziarah hari raya", localScript: "زِيَارَ رَرَايَا", category: "Kata Keterangan" },
  { localLanguage: "barakaka", indonesian: "kodok", localScript: "بَرَكَكَ", category: "Kata Hewan" },
  { localLanguage: "Zikiri isilamu", indonesian: "Zikir Islam", localScript: "زِكِيرِي اِسِلَمُو", category: "Kata Keterangan" },
  { localLanguage: "barasese", indonesian: "gelepar", localScript: "بَرَسَسَيْ", category: "Kata Sifat" },
  { localLanguage: "Zikiri isilamu", indonesian: "Zikir dalam Islam", localScript: "ذِكِرِي اِسِلَامُو", category: "Kata Keterangan" },
  { localLanguage: "barata", indonesian: "cadik", localScript: "بَرَتَ", category: "Kata Benda" },
  { localLanguage: "baroko", indonesian: "leher", localScript: "بَرُوكُو", category: "Kata Benda" },
  { localLanguage: "barua", indonesian: "muncrikari", localScript: "بَرُوَا", category: "Kata Kerja" },
  { localLanguage: "baruasa", indonesian: "kue dari tepung beras", localScript: "بَرُوَاسَ", category: "Kata Benda" },
  { localLanguage: "baruga", indonesian: "balairung", localScript: "بَرُڬَ", category: "Kata Keterangan" },
  { localLanguage: "baruta", indonesian: "nama desa di kecamtan Gu", localScript: "بَرُتَ", category: "Kata Keterangan" },
  { localLanguage: "basaraa", indonesian: "agung", localScript: "بَسَرَاا", category: "Kata Sifat" },
  { localLanguage: "basarapu", indonesian: "tonggak penegak", localScript: "بَسَرَاڤُ", category: "Kata Benda" },
  { localLanguage: "basi", indonesian: "mangkuk", localScript: "بَاسِي", category: "Kata Benda" },
  { localLanguage: "bata", indonesian: "batu genteng, rubuh", localScript: "بَتَ", category: "Kata Benda" },
  { localLanguage: "batabata", indonesian: "ragu-ragu", localScript: "بَتَابَتَ", category: "Kata Sifat" },
  { localLanguage: "batala", indonesian: "batal", localScript: "بَتَلَ", category: "Kata Sifat" },
  { localLanguage: "batata", indonesian: "tutur", localScript: "بَتَاتَ", category: "Kata Benda" },
  { localLanguage: "bate", indonesian: "serambi", localScript: "بَاتَيْ", category: "Kata Sifat" },
  { localLanguage: "batu", indonesian: "batu", localScript: "بَاتُ", category: "Kata Benda" },
  { localLanguage: "batua", indonesian: "budak sahaya", localScript: "بَاتُوَا", category: "Kata Keterangan" },
  { localLanguage: "bau-bau", indonesian: "bau-bau ibu kota Kabupaten Buton", localScript: "بَاوُبَاوُ", category: "Kata Benda" },
  { localLanguage: "bawine", indonesian: "perempuan", localScript: "بَاوِينَيْ", category: "Kata Keterangan" },
  { localLanguage: "bawo", indonesian: "atas", localScript: "بَاوُو", category: "Kata Benda" },
  { localLanguage: "bawu", indonesian: "babi", localScript: "بَاوُ", category: "Kata Hewan" },
  { localLanguage: "bawulu", indonesian: "buah sari", localScript: "بَاوُلُ", category: "Kata Buah" },
  { localLanguage: "be", indonesian: "awalan yang berarti akan", localScript: "بَيْ", category: "Kata Tanya" },
  { localLanguage: "bea", indonesian: "dia akan", localScript: "بَيْا", category: "Kata Kerja" },
  { localLanguage: "bea", indonesian: "bisu, dahulu", localScript: "بَيْا", category: "Kata Keterangan" },
  { localLanguage: "bengkele", indonesian: "bengkel", localScript: "بَنْڬَلَيْ", category: "Kata Tempat" },
  { localLanguage: "bengko", indonesian: "bengkok", localScript: "بَنْڬُو", category: "Kata Kerja" },
  { localLanguage: "bi'i", indonesian: "kemaluan", localScript: "بِيْاِي", category: "Kata Keterangan" },
  { localLanguage: "binata", indonesian: "binatang", localScript: "بِنَتَ", category: "Kata Hewan" },
  { localLanguage: "binciki", indonesian: "cubit", localScript: "بِنْچِكِي", category: "Kata Kerja" },
  { localLanguage: "bindu", indonesian: "cabut", localScript: "بِنْدُ", category: "Kata Kerja" },
  { localLanguage: "bingku", indonesian: "pacul", localScript: "بِنْڬُ", category: "Kata Benda" },
  { localLanguage: "binata", indonesian: "binatang", localScript: "بِنَتَ", category: "Kata Hewan" },
  { localLanguage: "binciki", indonesian: "cubit", localScript: "بِنْچِكِي", category: "Kata Tanya" },
  { localLanguage: "bindu", indonesian: "cabut", localScript: "بِنْدُ", category: "Kata Kerja" },
  { localLanguage: "bingku", indonesian: "pacul", localScript: "بِنْڬُ", category: "Kata Benda" },
  { localLanguage: "boke", indonesian: "ikat", localScript: "بُوكَيْ", category: "Kata Kerja" },
  { localLanguage: "bulusa", indonesian: "tempayan", localScript: "بُلُسَ", category: "Kata Benda" },
  { localLanguage: "buntuli", indonesian: "lari", localScript: "بُنْتُلِي", category: "Kata Kerja" },
  { localLanguage: "bungka", indonesian: "kepiting", localScript: "بُنْڬَ", category: "Kata Hewan" },
  { localLanguage: "bungkale", indonesian: "buka", localScript: "بُنْڬَكَلَيْ", category: "Kata Kerja" },
  { localLanguage: "biti", indonesian: "betis", localScript: "بِتِي", category: "Kata Keterangan" },
  { localLanguage: "biwi", indonesian: "pinggir, bibir", localScript: "بِوِي", category: "Kata Benda" },
  { localLanguage: "boasaka", indonesian: "ucap", localScript: "بُوَسَكَ", category: "Kata Kerja" },
  { localLanguage: "bela", indonesian: "luka", localScript: "بَلَ", category: "Kata Keterangan" },
  { localLanguage: "bengkala", indonesian: "langkah", localScript: "بَنْڬَلَ", category: "Kata Kerja" },
  { localLanguage: "bia", indonesian: "kain sarung", localScript: "بِيَا", category: "Kata Benda" },
  { localLanguage: "bio", indonesian: "telur ikan", localScript: "بِيُو", category: "Kata Benda" },
  { localLanguage: "bobuno", indonesian: "buah langsat", localScript: "بُبُنُو", category: "Kata Buah" },
  { localLanguage: "boco", indonesian: "kelambu", localScript: "بُچُو", category: "Kata Benda" },
  { localLanguage: "boke", indonesian: "ikat", localScript: "بُوكَيْ", category: "Kata Kerja" },
  { localLanguage: "bolu", indonesian: "kue bolu", localScript: "بُولُ", category: "Kata Benda" },
  { localLanguage: "bone", indonesian: "pasir", localScript: "بُونَيْ", category: "Kata Benda" },
  { localLanguage: "bose", indonesian: "dayung, berlayar", localScript: "بُوسَيْ", category: "Kata Benda" },
  { localLanguage: "bue", indonesian: "ayun", localScript: "بُوَيْ", category: "Kata Kerja" },
  { localLanguage: "buea", indonesian: "buaya", localScript: "بُوَيْا", category: "Kata Hewan" },
  { localLanguage: "bugisi", indonesian: "bugis", localScript: "بُڬِسِي", category: "Kata Keterangan" },
  { localLanguage: "buke", indonesian: "penuh", localScript: "بُكَيْ", category: "Kata Kerja" },
  { localLanguage: "bulawa", indonesian: "emas", localScript: "بُلَوَا", category: "Kata Benda" },
  { localLanguage: "buli-buli", indonesian: "anus", localScript: "بُلِيبُلِي", category: "Kata Tubuh" },
  { localLanguage: "bulua", indonesian: "rambut", localScript: "بُلُوَا", category: "Kata Tubuh" },
  { localLanguage: "bulumata", indonesian: "bulumata", localScript: "بُلُومَتَ", category: "Kata Tubuh" },
  { localLanguage: "bulumuncu", indonesian: "kumis", localScript: "بُلُومُنْچُ", category: "Kata Tubuh" },
  { localLanguage: "bulusa", indonesian: "tempayan", localScript: "بُلُسَ", category: "Kata Benda" },
  { localLanguage: "bungkalea", indonesian: "dibuka", localScript: "بُنْڬَكَلَا", category: "Kata Kerja" },
  { localLanguage: "bungkolo", indonesian: "kutu tanah", localScript: "بُنْڬُولُو", category: "Kata Hewan" },
  { localLanguage: "bungku", indonesian: "bungkuk", localScript: "بُنْڬُ", category: "Kata Kerja" },
  { localLanguage: "bungkusu", indonesian: "bungkus", localScript: "بُنْڬُسُ", category: "Kata Kerja" },
  { localLanguage: "bunia", indonesian: "burung elang", localScript: "بُنِيَا", category: "Kata Hewan" },
  { localLanguage: "buniaka", indonesian: "sembunyi", localScript: "بُنِيَاڬَ", category: "Kata Kerja" },
  { localLanguage: "calo", indonesian: "calon", localScript: "چَالُو", category: "Kata Keterangan" },
  { localLanguage: "cama", indonesian: "camat, kawat pembakar candu", localScript: "چَمَ", category: "Kata Keterangan" },
  { localLanguage: "celenga", indonesian: "celengan", localScript: "چَلَنْڬَ", category: "Kata Benda" },
  { localLanguage: "cindolo", indonesian: "cendol", localScript: "چِنْدُلُو", category: "Kata Benda" },
  { localLanguage: "cirikaeya", indonesian: "serikaya", localScript: "چِرِكَاَيَا", category: "Kata Buah" },
  { localLanguage: "cobe", indonesian: "sambal", localScript: "چُبَيْ", category: "Kata Benda" },
  { localLanguage: "coco", indonesian: "cocok", localScript: "چُچُو", category: "Kata Benda" },
  { localLanguage: "colo", indonesian: "korek api", localScript: "چُلُو", category: "Kata Benda" },
  { localLanguage: "burusi", indonesian: "mengais", localScript: "بُرُسِي", category: "Kata Kerja" },
  { localLanguage: "buroto", indonesian: "nyamuk", localScript: "بُرُوتُو", category: "Kata Hewan" },
  { localLanguage: "coro", indonesian: "corong", localScript: "چُرُو", category: "Kata Benda" },
  { localLanguage: "cucuru", indonesian: "cucur(kue)", localScript: "چُچُرُ", category: "Kata Benda" },
  { localLanguage: "curabi", indonesian: "serabi", localScript: "چُرَابِي", category: "Kata Benda" },
  { localLanguage: "daakana", indonesian: "mengapa", localScript: "دَااَكَنَ", category: "Kata Tanya" },
  { localLanguage: "daampo", indonesian: "nanti", localScript: "دَااَمْڤُو", category: "Kata Keterangan" },
  { localLanguage: "dadara", indonesian: "kue dadar", localScript: "دَادَرَ", category: "Kata Benda" },
  { localLanguage: "daeng", indonesian: "panggilan untuk orang makasar", localScript: "دَايَنْڬ", category: "Kata Keterangan" },
  { localLanguage: "daga", indonesian: "dagang", localScript: "دَاڬَا", category: "Kata Kerja" },
  { localLanguage: "dala", indonesian: "jalan", localScript: "دَالَ", category: "Kata Kerja" },
  { localLanguage: "dalika", indonesian: "tungku", localScript: "دَلِكَا", category: "Kata Benda" },
  { localLanguage: "danda", indonesian: "dandang", localScript: "دَنْدَ", category: "Kata Benda" },
  { localLanguage: "daoa", indonesian: "pasar", localScript: "دَاوَا", category: "Kata Benda" },
  { localLanguage: "dati", indonesian: "jati", localScript: "دَتِي", category: "Kata Benda" },
  { localLanguage: "dei", indonesian: "cepat", localScript: "دَيْ", category: "Kata Keterangan" },
  { localLanguage: "dela", indonesian: "lidah", localScript: "دَيْلَ", category: "Kata Benda" },
  { localLanguage: "dela marambe", indonesian: "lidah panjang", localScript: "دَيْلَ مَرَمْبَيْ", category: "Kata Tubuh" },
  { localLanguage: "dhagu", indonesian: "dagu", localScript: "دْهَاڬُ", category: "Kata Tubuh" },
  { localLanguage: "dhai", indonesian: "tipu", localScript: "دْهَاي", category: "Kata Sifat" },
  { localLanguage: "dhalima", indonesian: "tumbuhan delima", localScript: "دْهَلِمَ", category: "Kata Buah" },
  { localLanguage: "dha'u", indonesian: "zakar(kemaluan laki-laki)", localScript: "دْهَاُ", category: "Kata Tubuh" },
  { localLanguage: "dhoa", indonesian: "doa", localScript: "دْهُوَا", category: "Kata Keterangan" },
  { localLanguage: "dhoti", indonesian: "ilmu hitam(guna-guna)", localScript: "دْهُوتِي", category: "Kata Keterangan" },
  { localLanguage: "dhudhu", indonesian: "payu dara", localScript: "دْهُدْهُ", category: "Kata Tubuh" },
  { localLanguage: "dhunia", indonesian: "dunia", localScript: "دْهُنِيَا", category: "Kata Keterangan" },
  { localLanguage: "dhurhaka", indonesian: "durhaka", localScript: "دْهُرْهَكَ", category: "Kata Sifat" },
  { localLanguage: "dingku", indonesian: "sentu", localScript: "دِنْڬُ", category: "Kata Kerja" },
  { localLanguage: "donga", indonesian: "muncul", localScript: "دُونْڬَ", category: "Kata Kerja" },
  { localLanguage: "dopi", indonesian: "papan", localScript: "دُوڤِي", category: "Kata Benda" },
  { localLanguage: "dosa", indonesian: "utang", localScript: "دُوسَ", category: "Kata Benda" },
  { localLanguage: "dotoro", indonesian: "dokter", localScript: "دُوتُرُو", category: "Kata Keterangan" },
  { localLanguage: "fitua", indonesian: "perkiraan", localScript: "فِتُوَا", category: "Kata Keterangan" },
  { localLanguage: "gaebu", indonesian: "gaib", localScript: "ڬَايْبُ", category: "Kata Keterangan" },
  { localLanguage: "gai", indonesian: "gait", localScript: "ڬَاي", category: "Kata Kerja" },
  { localLanguage: "gaja", indonesian: "gajah", localScript: "ڬَاجَ", category: "Kata Hewan" },
  { localLanguage: "gambara", indonesian: "gambar", localScript: "ڬَمْبَرَ", category: "Kata Kerja" },
  { localLanguage: "gampa", indonesian: "mudah", localScript: "ڬَمْڤَ", category: "Kata Keterangan" },
  { localLanguage: "garisi", indonesian: "garis", localScript: "ڬَرِسِي", category: "Kata Benda" },
  { localLanguage: "garoba", indonesian: "gerobak", localScript: "ڬَرُبَ", category: "Kata Benda" },
  { localLanguage: "hadia", indonesian: "hadiah", localScript: "هَدِيَا", category: "Kata Benda" },
  { localLanguage: "insafu", indonesian: "insaf", localScript: "اِنْسَفُ", category: "Kata Sifat" },
  { localLanguage: "isinini", indonesian: "senin(hari)", localScript: "اِسِنِنِي", category: "Kata Hari" },
  { localLanguage: "jahanamu", indonesian: "neraka", localScript: "جَهَنَمُ", category: "Kata Keterangan" },
  { localLanguage: "kalambe", indonesian: "gadis", localScript: "كَلَمْبَيْ", category: "Kata Tubuh" },
  { localLanguage: "kalimbungu", indonesian: "kelap muda", localScript: "كَلِمْبُنْڬُ", category: "Kata Benda" },
];

async function main() {
  console.log("🌱 Seeding database...");

  // Super admin
  const hashedPassword = await bcrypt.hash("admin123", 10);
  const admin = await prisma.user.upsert({
    where: { id: "super-admin-seed" },
    update: {},
    create: {
      id: "super-admin-seed",
      username: "admin",
      name: "Administrator",
      password: hashedPassword,
      role: "SUPER_ADMIN",
    },
  });
  console.log(`✅ User admin: ${admin.username} / admin123`);

  // Kategori — upsert via name (unique)
  const categoryMap: Record<string, string> = {};
  for (const name of CATEGORIES) {
    const cat = await prisma.category.upsert({
      where: { name },
      update: {},
      create: { name },
    });
    categoryMap[name] = cat.id;
  }
  console.log(`✅ ${CATEGORIES.length} kategori dibuat`);

  // Kata — skip duplikat berdasarkan kombinasi localLanguage + indonesian + categoryId
  let created = 0;
  for (const word of [...WORDS, ...WORDS_XLSX]) {
    const categoryId = categoryMap[word.category];
    if (!categoryId) {
      console.warn(`⚠️  Kategori tidak ditemukan: ${word.category}`);
      continue;
    }
    const existing = await prisma.word.findFirst({
      where: { localLanguage: word.localLanguage, indonesian: word.indonesian, categoryId },
    });
    if (!existing) {
      await prisma.word.create({
        data: {
          indonesian: word.indonesian,
          localLanguage: word.localLanguage,
          localScript: word.localScript,
          categoryId,
        },
      });
      created++;
    }
  }
  console.log(`✅ ${created} kata dibuat`);

  // Sync meta
  await prisma.syncMeta.upsert({
    where: { key: "sync_version" },
    update: {},
    create: { key: "sync_version", value: "1" },
  });
  console.log("✅ Sync meta diinisialisasi");
  console.log("🎉 Seeding selesai!");
}

main()
  .catch((e) => {
    console.error("❌ Seeding gagal:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
